stages:
  get_mitre_data:
    cmd: python src/pipeline/01_get_mitre_data.py
    deps:
    - src/pipeline/01_get_mitre_data.py
    - ${get_data.mitre_attack_fn}
    params:  
    - get_data.divide_paras
    outs:
    - ${get_data.data_mitre_fn}
    - ${get_data.data_mitre_attack_proc_fn}
    - ${get_data.label2tactic_fn}
  get_add_data:
    cmd: python src/pipeline/02_get_add_data.py
    deps:
    - ${get_data.data_mitre_fn}
    - ${get_data.tram_fn}
    - ${get_data.data_mitre_attack_proc_fn}
    - ${get_data.cti_hal_dn}
    - ${get_data.rep_dn}
    - ${get_data.label2tactic_fn}
    - src/pipeline/02_get_add_data.py
    params:
    - get_data.ignore_subt
    - get_data.use_tram_f
    - get_data.use_reports_f
    - get_data.add_cti_hal
    outs:
    - ${get_data.data_fn}
  split_data:
    cmd: python src/pipeline/03_split_data.py
    deps:
    - src/pipeline/03_split_data.py
    params:
    - val_nmitr
    outs:
    - ${get_data.ttp_mlb_fn}
    - ${get_data.split_fn}
  setup_storage:
    cmd: python src/pipeline/04_setup_storage.py
    deps:
    - ${get_data.data_fn}
    - src/pipeline/04_setup_storage.py
    params:
    - storage.smodel_path
    - storage.db_type
    - storage.re_write_db
    outs:
    - ${storage.db_path}
    - ${storage.bm25_path}
  train_eval:
    cmd: python src/pipeline/05_train_eval.py
    deps:
    - ${storage.bm25_path}
    - ${storage.db_path}
    - src/pipeline/05_train_eval.py
    params:
    - train_eval.model
    - train_eval.rag_type
    - train_eval.rag_k
    - train_eval.lambda_mult
    - train_eval.fetch_k
    - train_eval.use_bert
    metrics:
    - ${train_eval.m_fn}